### ISSUE TITLE
Date showing up on Quick Play Map Checker as NaN errors.

### ISSUE THREAD

**Issue by Finbae** [BonkLeagues/bonkleagues.github.io#3]
Device: its_magic's tablet (iPad?)
Issue: On the Quick Play Map Checker, every single map's created date shows up as 'Created: NaN undefined NaN - NaN:NaN:NaN'.

https://cdn.discordapp.com/attachments/395616425139503124/407097184027279360/image.png

Cannot reproduce on PC.

**Comment by WheatleyTheCoder** [comment]
Works on my PC, so I'm just assuming it's Safari being terrible at handling dates.

**Comment by Finbae** [comment]
@WheatleyTheCoder Seems to be a common issue with Safari judging by a quick Google search https://www.google.co.uk/search?q=safari+date+handling. Will begin work on a fix later today.
